//
//  ContentView.swift
//  RedactedDemo
//
//  Created by Shriram Ghadge on 11/03/23.
//

import SwiftUI

struct ContentView: View {
    
    @State private var isLoading = false
    
    var body: some View {
        VStack(alignment: .center, spacing: 12){
            
            Spacer()
            Spacer()
            
            VStack{
                Image("profile-pic")
                    .resizable()
                    .frame(width: 100, height: 100)
                    .clipShape(Circle())
                    .overlay(Circle().stroke(Color.black, lineWidth: 2))
                    .shadow(radius: 10)
                
                Text("Shiru99")
                    .font(.title)
                
            }
            
            Spacer()
            
            VStack(alignment: .leading, spacing: 15) {
                Text("About Me")
                    .font(.title2)
                    .unredacted()
                
                Text("Autogenerated : I am a software developer and a tech enthusiast. I love to learn new things and share my knowledge with others. I am a self taught developer and I am always looking for new opportunities to learn and grow.")
                    .font(.body)
                
                VStack(alignment: .leading, spacing: 10){
                    HStack{
                        Image(systemName: "location")
                            .unredacted()

                        Text("India")
                            .font(.body)
                        
                    }
                    
                    HStack{
                        Image(systemName: "phone")
                            .unredacted()
                        Text("9876543210")
                            .font(.body)
                        
                    }
                    
                    HStack{
                        Image(systemName: "mail")
                            .unredacted()
                        Text("pls.visit@github.in")
                            .font(.body)
                        
                    }
                    
                    HStack{
                        Image(systemName: "network")
                            .unredacted()
                        Text("https://github.com/Shiru99")
                            .font(.body)
                        
                    }
                    
                }.padding()
                
            }.padding(.horizontal, 36)
            
            Link("Visit GitHub",destination: URL(string: "https://github.com/shiru99")!)
                .foregroundColor(.white)
                .padding()
                .background(Color.blue)
                .cornerRadius(10)
                .padding()
                .disabled(isLoading)
            
            Spacer()
        }
        .redacted(reason: isLoading ? .placeholder : [])
        .onAppear{
            fakeNetworkCall()
        }
    }
    
    func fakeNetworkCall(){
        self.isLoading = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
            self.isLoading = false
            print("Network call completed")
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
